### PR TITLE
Fix typo "UnsupporedError" to "UnsupportedError"

### PR DESCRIPTION
**Pull request by unasuke**
## TODO
- [x] Add test case

### CODE REVIEW

**Comment by ksss** [comment]
@unasuke  Grazie!
Would you also fix other `UnsupporedError` in attachment.rb ?
(We should add some tests...)

**Comment by unasuke** [comment]
@ksss Fixed all typo, sorry. We need some test surely. I'll add that. So I change this pull-req to draft.

**Comment by unasuke** [comment]
@ksss Test added! Could you review it again?

**Comment by ksss** [comment]
@unasuke GREAT! Thanks!

**Pull request merged**
